language: ruby
sudo: false
cache: bundler

rvm:
 - 2.0
 - 2.1
 - 2.2.4
 - 2.3.0
 - ruby-head
 - jruby
 - jruby-head

env:
  - JRUBY_OPTS="--2.0"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
