language: ruby
cache: bundler

rvm:
 - 2.0
 - 2.1
 - 2.2.4
 - 2.3.0
 - ruby-head
 - jruby
 - jruby-head

env:
  - JRUBY_OPTS="--2.0"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true

script:
  - bundle install
  - cp spec/environment.rb.sample spec/environment.rb
  - sed -i "s~YOUR_STORAGE_ACCOUNT_NAME~${STORAGE_ACCOUNT_NAME}~g" spec/environment.rb
  - sed -i "s~YOUR_STORAGE_ACCESS_KEY~${STORAGE_ACCESS_KEY}~g" spec/environment.rb
  - sed -i "s~YOUR_CONTAINER_NAME~test~g" spec/environment.rb
  - rspec
